### ISSUE TITLE
Bt app messed up

### ISSUE THREAD

**Issue by ShihabZzz** [ResurrectionRemix/android_packages_apps_Bluetooth#1]
https://del.dog/reyanaxoli.makefile

[ 80% 113/140] Building Kernel Config
make: Entering directory '/home/shihab_riadn/rr/kernel/xiaomi/markw'
make[1]: Entering directory '/home/shihab_riadn/rr/out/target/product/markw/obj/KERNEL_OBJ'
  GEN     ./Makefile
#
# configuration written to .config
#
make[1]: Leaving directory '/home/shihab_riadn/rr/out/target/product/markw/obj/KERNEL_OBJ'
make: Leaving directory '/home/shihab_riadn/rr/kernel/xiaomi/markw'
make: Entering directory '/home/shihab_riadn/rr/kernel/xiaomi/markw'
make[1]: Entering directory '/home/shihab_riadn/rr/out/target/product/markw/obj/KERNEL_OBJ'
  GEN     ./Makefile
scripts/kconfig/conf  --savedefconfig=defconfig Kconfig
make[1]: Leaving directory '/home/shihab_riadn/rr/out/target/product/markw/obj/KERNEL_OBJ'
make: Leaving directory '/home/shihab_riadn/rr/kernel/xiaomi/markw'
[ 81% 114/140] Target Java: /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/classes-full-debug.jar
FAILED: /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/classes-full-debug.jar 
/bin/bash -c "(rm -f /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/classes-full-debug.jar ) && (rm -rf /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/classes /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/anno ) && (mkdir -p /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/ ) && (mkdir -p /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/classes /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/anno ) && (/home/shihab_riadn/rr/out/soong/host/linux-x86/bin/zipsync -d /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/srcjars -l /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/srcjar-list -f \"*.java\"  /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/aapt2.srcjar ) && (if [ -s /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/java-source-list -o -s /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/srcjar-list ] ; then /home/shihab_riadn/rr/out/soong/host/linux-x86/bin/soong_javac_wrapper  prebuilts/jdk/jdk9/linux-x86/bin/javac -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath \"\" -g -XDskipDuplicateBridges=true -XDstringConcat=inline -encoding UTF-8   -bootclasspath /home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/classes-header.jar:/home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/classes-header.jar:/home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/classes-header.jar:/home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-header.jar:/home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/classes-header.jar:/home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar  -classpath /home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/javax.obex_intermediates/classes-header.jar:/home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/services.net_intermediates/classes-header.jar:/home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/telephony-common_intermediates/classes-header.jar:/home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/com.android.vcard_intermediates/classes-header.jar:/home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/bluetooth.mapsapi_intermediates/classes-header.jar:/home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/sap-api-java-static_intermediates/classes-header.jar:/home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/services.net_intermediates/classes-header.jar:/home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/libprotobuf-java-lite_intermediates/classes-header.jar:/home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/bluetooth-protos-lite_intermediates/classes-header.jar:/home/shihab_riadn/rr/out/target/common/obj/JAVA_LIBRARIES/android-support-v4_intermediates/classes-header.jar  -d /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/classes -s /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/anno  -source 1.8 -target 1.8 -g:source,lines  \\@/home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/java-source-list \\@/home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/srcjar-list || ( rm -rf /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/classes ; exit 41 ) fi ) && (prebuilts/jdk/jdk9/linux-x86/bin/jar -cf /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/classes-full-debug.jar     @<(find /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/classes -type f | sort | build/soong/scripts/jar-args.sh /home/shihab_riadn/rr/out/target/common/obj/APPS/Bluetooth_intermediates/classes; echo \"-C /home/shihab_riadn/rr/out/empty .\") )"
packages/apps/Bluetooth/src/com/android/bluetooth/a2dp/A2dpCodecConfig.java:78: error: cannot find symbol
                  BluetoothCodecConfig.CHANNEL_MODE_DUAL_CHANNEL, 0 /* codecSpecific1 */,
                                      ^
  symbol:   variable CHANNEL_MODE_DUAL_CHANNEL
  location: class BluetoothCodecConfig
packages/apps/Bluetooth/src/com/android/bluetooth/a2dp/A2dpService.java:937: error: cannot find symbol
                            && (config.getChannelMode() & config.CHANNEL_MODE_DUAL_CHANNEL)
                                                                ^
  symbol:   variable CHANNEL_MODE_DUAL_CHANNEL
  location: variable config of type BluetoothCodecConfig
packages/apps/Bluetooth/src/com/android/bluetooth/a2dp/A2dpService.java:938: error: cannot find symbol
                                   == config.CHANNEL_MODE_DUAL_CHANNEL);
                                            ^
  symbol:   variable CHANNEL_MODE_DUAL_CHANNEL
  location: variable config of type BluetoothCodecConfig
3 errors
[ 82% 115/140] Building Kernel
make: Entering directory '/home/shihab_riadn/rr/kernel/xiaomi/markw'
make[1]: Entering directory '/home/shihab_riadn/rr/out/target/product/markw/obj/KERNEL_OBJ'
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Using /home/shihab_riadn/rr/kernel/xiaomi/markw as source for kernel
  CALL    /home/shihab_riadn/rr/kernel/xiaomi/markw/scripts/checksyscalls.sh
make[2]: 'include/generated/vdso-offsets.h' is up to date.
  CHK     include/generated/compile.h
/home/shihab_riadn/rr/kernel/xiaomi/markw/kernel/Makefile:150: *** No X.509 certificates found ***
  CHK     kernel/config_data.h
  DTC     arch/arm64/boot/dts/qcom/msm8953-qrd-markw.dtb
  CAT     arch/arm64/boot/Image.gz-dtb
make[1]: Leaving directory '/home/shihab_riadn/rr/out/target/product/markw/obj/KERNEL_OBJ'
make: Leaving directory '/home/shihab_riadn/rr/kernel/xiaomi/markw'
Building DTBs
make: Entering directory '/home/shihab_riadn/rr/kernel/xiaomi/markw'
make[1]: Entering directory '/home/shihab_riadn/rr/out/target/product/markw/obj/KERNEL_OBJ'
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Using /home/shihab_riadn/rr/kernel/xiaomi/markw as source for kernel
  CALL    /home/shihab_riadn/rr/kernel/xiaomi/markw/scripts/checksyscalls.sh
make[2]: 'include/generated/vdso-offsets.h' is up to date.
make[1]: Leaving directory '/home/shihab_riadn/rr/out/target/product/markw/obj/KERNEL_OBJ'
make: Leaving directory '/home/shihab_riadn/rr/kernel/xiaomi/markw'
ninja: build stopped: subcommand failed.
04:07:05 ninja failed with: exit status 1

#### failed to build some targets (01:28 (mm:ss)) ####

**Comment by DahakePL** [comment]
Did you fix it?
